# Generated by Django 4.2.11 on 2026-01-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValveDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文档名称")),
                (
                    "file",
                    models.FileField(upload_to="documents/", verbose_name="PDF 文件"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartridgeValve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="型号名称")),
                ("series", models.CharField(max_length=100, verbose_name="系列")),
                ("description", models.TextField(blank=True, verbose_name="产品描述")),
                (
                    "application",
                    models.CharField(blank=True, max_length=200, verbose_name="应用场景"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.valvedocument",
                        verbose_name="技术文档",
                    ),
                ),
            ],
        ),
    ]
