# Generated by Django 4.2.28 on 2026-02-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartridgevalve",
            options={
                "verbose_name": "Cartridge Valve",
                "verbose_name_plural": "Cartridge Valves",
            },
        ),
        migrations.AlterModelOptions(
            name="valvedocument",
            options={
                "verbose_name": "Valve Document",
                "verbose_name_plural": "Valve Documents",
            },
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="cavity",
            field=models.CharField(
                blank=True,
                help_text="Installation cavity dimensions",
                max_length=100,
                verbose_name="Cavity",
            ),
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="material",
            field=models.CharField(
                blank=True, default="Steel", max_length=100, verbose_name="Material"
            ),
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="max_flow",
            field=models.FloatField(
                blank=True,
                help_text="Maximum flow rate in l/min",
                null=True,
                verbose_name="Max Flow (l/min)",
            ),
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="max_pressure",
            field=models.FloatField(
                blank=True,
                help_text="Maximum operating pressure in bar",
                null=True,
                verbose_name="Max Pressure (bar)",
            ),
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/thumbnails/",
                verbose_name="Product Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="valvedocument",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("datasheet", "Datasheet"),
                    ("drawing", "Drawing"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="datasheet",
                max_length=20,
                verbose_name="Document Type",
            ),
        ),
        migrations.AddField(
            model_name="valvedocument",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="e.g. v1.0, Rev A",
                max_length=20,
                verbose_name="Version",
            ),
        ),
        migrations.AlterField(
            model_name="cartridgevalve",
            name="application",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Application"
            ),
        ),
        migrations.AlterField(
            model_name="cartridgevalve",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="cartridgevalve",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="cartridgevalve",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.valvedocument",
                verbose_name="Technical Documents",
            ),
        ),
        migrations.AlterField(
            model_name="cartridgevalve",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Model Name"),
        ),
        migrations.AlterField(
            model_name="cartridgevalve",
            name="series",
            field=models.CharField(max_length=100, verbose_name="Series"),
        ),
        migrations.AlterField(
            model_name="valvedocument",
            name="file",
            field=models.FileField(upload_to="documents/", verbose_name="PDF File"),
        ),
        migrations.AlterField(
            model_name="valvedocument",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Document Title"),
        ),
        migrations.AlterField(
            model_name="valvedocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="cartridgevalve",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
                verbose_name="Category",
            ),
        ),
    ]
