# Generated by Django 5.2.11 on 2026-02-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="分类图片",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "model_code",
                    models.CharField(
                        help_text="唯一标识符，例如 CBEG-LJN",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="型号代码",
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=50, verbose_name="系列"),
                ),
                ("description", models.TextField(blank=True, verbose_name="产品描述")),
                (
                    "cavity",
                    models.CharField(
                        blank=True,
                        help_text="例如 T-10A",
                        max_length=50,
                        verbose_name="插孔标准",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, default="Steel", max_length=50, verbose_name="材质"
                    ),
                ),
                (
                    "schematic_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/schematics/",
                        verbose_name="原理图",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/images/",
                        verbose_name="产品实物图",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储键值对形式的技术参数",
                        verbose_name="技术参数",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否上架")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
            },
        ),
        migrations.CreateModel(
            name="PerformanceCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curve_type",
                    models.CharField(
                        help_text="例如：压降 vs 流量", max_length=50, verbose_name="曲线类型"
                    ),
                ),
                (
                    "data_points",
                    models.JSONField(
                        default=list,
                        help_text="存储 [{'x': 10, 'y': 20}, ...] 格式的数据",
                        verbose_name="数据点",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_curves",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "性能曲线",
                "verbose_name_plural": "性能曲线",
            },
        ),
        migrations.CreateModel(
            name="ProductAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="products/attachments/", verbose_name="文件"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("datasheet", "数据表"),
                            ("drawing", "图纸"),
                            ("manual", "手册"),
                            ("other", "其他"),
                        ],
                        default="datasheet",
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="标题"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品附件",
                "verbose_name_plural": "产品附件",
            },
        ),
    ]
